import Link from 'next/link';
import { supabase } from '@/utils/supabaseClient';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Pacifico } from 'next/font/google';
import Image from 'next/image';
import { motion, useTime, useTransform } from 'framer-motion';
import { useGetSessionUserQuery } from '@/redux/users/checkRegisterSlice';
import LoadingSpinner from '@/components/LoadingSpinner';
import { useEffect, useState } from 'react';


const pacifico = Pacifico({ subsets: ['latin'], weight: '400' });

export default function Home() {
  const { data, error, isLoading, isSuccess } =
    useGetSessionUserQuery('session');
  const [name, setName] = useState('');
  const router = useRouter();
  const time = useTime();
  const rotate = useTransform(time, [0, 4000], [0, 360], { clamp: false });

const imageStyle = {
  width: '100',
  height: '50'
}

  const checkName = () => {
    if (isSuccess) {
      if(data.session == null){
        router.push('/login')
      }
      setName(data.session?.user.email);
    }
  };

  useEffect(() => {
    checkName();
  }, [data]);

  async function Logout() {
    const { error } = await supabase.auth.signOut();
    router.reload()
  }

  return (
    <div>
      <div>
        {error && <p>Is Error help me please...</p>}
        {isLoading && <LoadingSpinner />}
      </div>
      {isSuccess ? (
        <>
          <Head>
            <title>Todoshka</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>
          <div className="flex flex-col h-screen items-center justify-center">
            <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/70 z-[2] " />
            <motion.div style={{ rotate }} className="pb-10 z-[2]">
              <Image  width={100} height={50} src="/cat.png" alt="cat"  />
            </motion.div>
            <div
              className={`text-2xl md:text-4xl bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500 z-[2] ${pacifico.className} text-center`}
            >
              <div className="underline">
                <Link href="/todos">Welcome Todoshka...</Link>
              </div>
              <motion.div
                animate={{ x: 100 }}
                transition={{ ease: 'easeOut', duration: 2 }}
                className="text-gray-400 mr-20 py-2 text-xl bg-clip-text text-transparent bg-gradient-to-r from-green-500 to-pink-500 z-[2"
              >
                {name}
              </motion.div>
            </div>
            <div
              className={`fixed bottom-7 font-bold text-2xl text-gray-500 hover:text-red-400 z-[2] ${pacifico.className}`}
            >
              <button onClick={Logout}>Exit.</button>
            </div>
            <div className="fixed bottom-0 text-white text-xs z-[2] pb-2">
              Created by dreamer v1.0
            </div>
          </div>
        </>
      ) : (
        <div className="flex justify-center items-center h-screen font-bold text-2xl  text-white">
          <Link href="/login">back to Login...</Link>
        </div>
      )}
    </div>
  );
}
